apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: linkback-poi-map-app-dev
  annotations:
    argocd/app-name: linkback-poi-map-app-dev
    backstage.io/kubernetes-id: linkback-poi-map-app
    backstage.io/kubernetes-namespace: linkback
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/linkback-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/linkback/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/linkback/deployments/linkback-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/linkback-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://linkback-poi-map-app-linkback.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/linkback"
  system: workshop-system-linkback
  consumesApis:
    - gateway-api-linkback
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-linkback
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/linkback"
